name: Java CI using Gradle Wrapper

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 15
        uses: actions/setup-java@v3
        with:
          java-version: '15'
          distribution: 'adopt'

      # Install Xvfb for avoiding X11 window server AWTError when running tests (https://arbitrary-but-fixed.net/2022/01/21/headless-gui-github-actions.html)
      - name: Setup xvfb for X11 window server
        run: Xvfb :1 -screen 0 1600x1200x24 &

      # Prepare MPS
      - name: Download and Prepare MPS
        run: sh ./gradlew prepareMps

      # Build Project
      - name: Build Project
        run: sh ./gradlew mpsBuild

      # Test Project
      - name: Test Project
        run: sh ./gradlew mpsTest
        env:
          DISPLAY: :1

      # Stop Xvfb
      - name: Tear down xvfb
        run: killall Xvfb

      # Snapshot Release
      - name: Create Snapshot Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automatic release build on every successful commit
          draft: true
          prerelease: true
